language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
after_success:
- "./gradlew cobertura coveralls --stacktrace"
- test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_TAG}" != "" && ./gradlew
  bintrayUpload --stacktrace
env:
  global:
  - secure: fary8Fe2flDhSzdvNAZ7V5TcnyF+J4vB8ldkCuiH2dDFc3GVr60kdNwWmbkAgz9Rbc9niSYW9vL6bbzAyQCbTjVJ6U0nIwxr88Jdzg9gtgb9TZtgSkvL78Mds4h1N8o0nUAWmQWc/dcTNiZM0wqH95EfOcqeK/neruA/JCmIGdXOvUZUMV2KVvbpiozDjOqj4ErbRWDpDEkzE6nAR1HbjROnow4euTzH5i5SgVzyGfnI2D2ibnbbg12wktYqBUIJETNOw4Ct3WDvwmnCMKRLFAA4vtuUxOc5RbtehpHasqkPgt638zlNaVIXHIqJpwK4n5QQm+sMmFh+nUw/CSyNYEXWD/92fzvjfyqsQdDOcTvfGShLpHQgaCnzv+66D2QUrtBPvC/qi5aM48gNlKipUm9GvsFW3p4A4LMioQUZyl+F8F+UVl3IhqMjekR9iG/FgoksJSnFnMLIvYbDBNgN0My/GGk+AGQiWC8KSgfPKlk1j4pDbgs4VMSsB+yL3ar9RbqFqsj9oHqVB0TEhzfz84xiigUMNPWDauveuLZ5JpifR6RSvRc+l73B3WjXwIQTKYGY/OzoaHEMK128EH7zfMi1ElQpi9boQEWtNMckEJ8u6WAQB12hwMsSmL8SeLbf/ioK7YvoTAQ+YxLzty6RxGwo5SjGfPaMBPhzKP6LzK0=
  - secure: TfOsrjuvfr64fuidsQ7WpqLNcX2Zv7/s1tCh9inbcuc3VEOHlMQgcE5soC9SxrlEFxYRlTSyz5eQhglnin3zMY9gaC697m0VOgGQdyqsoy0uyT4RGJT3M0ilm4OJL3gTWp1W0+qKqIjESW/CJVL6n9M9mD2E5wShQBUkTdK+J9PzDDCZ0sKfHaBfAFIGGao2WxwmUvE7HHjwfX8iVn9VoURy+LaA1gDLTwl7XWvQhw60yH5rsAFjSt2OHzd02xRUnlrxv7Z9sWV/GqQYWKj9m4x0AD7SV8ocsMAoJvi5KeN+yzOiC2HTAkC0VukOwYZJu+j/yHUBvgzHO48NRLjrTZweNGsGipCTJNUaH0W+4QOl2o8eok2nPnr79IIJGLzmz66PKFGMZtRhDD6cC09EVpVBOg6n1n+tRawtJtjnW3a3ehTAjTdaLd0sJmh7WspSiolQtFFIExBoNT1ter6C+p20yn2yKEP4hL+kyUOPgPGEIzUrsLwqgh1L+NlE0Wu7AM4weWM/PYv985sDA2k4vXplIFdgiaVdUB+R+nc0P0HWI9h8VK/yB/71QQIvKRIxYpjreemGsgtnRpAODdd003TytXonx+DJWiAuRgLOdC/bgcbAYmSyCdD/OU90ZQxO1haz97PmrwhMDOwsCSExUodCsaaQ8Xk2+9/QLIQuoGg=
